Ajout de bdd ;)
Bethoth/Dico-abreviations-et-acronymes pull request #4
Opened 2020-04-12 01:04 UTC by Ayfri

2020-04-12 09:23 UTC, Bethoth requested changes
J'ai commenté ce qui n'allait pas.

2020-04-12 09:23 UTC, Bethoth commented on B/bdd.md
> +# BA
pourquoi as-tu mis "BA" et pas "BDD" ??

2020-04-12 12:16 UTC, Ayfri commented
J'ai fail x)

2020-04-12 12:52 UTC, Bethoth commented
Tu pourrais le modifier que je puisse merge du coup ?

2020-04-13 09:02 UTC, Bethoth approved these changes
C'est parfait. Merci.

2020-04-13 09:02 UTC, merged